FROM node:18-slim

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY . .

# Add ARG statements before ENV
ARG AUTH_CLIENT_ID
ARG AUTH_CLIENT_SECRET
ARG SESSION_SECRET
ARG CALLBACK_URL
ARG ALLOWED_GITHUB_USERS
ARG DROPLET_IP
ARG DROPLET_USER
ARG DROPLET_SSH_KEY

# Environment variables
ENV PORT=3000
ENV NODE_ENV=production
ENV AUTH_CLIENT_ID=$AUTH_CLIENT_ID
ENV AUTH_CLIENT_SECRET=$AUTH_CLIENT_SECRET
ENV SESSION_SECRET=$SESSION_SECRET
ENV CALLBACK_URL=$CALLBACK_URL
ENV ALLOWED_GITHUB_USERS=$ALLOWED_GITHUB_USERS
ENV DROPLET_IP=$DROPLET_IP
ENV DROPLET_USER=$DROPLET_USER
ENV DROPLET_SSH_KEY=$DROPLET_SSH_KEY

EXPOSE 3000

CMD ["node", "src/index.js"] 