name: deploy cb-front

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3

      # Build and push Docker image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}/cb-front:latest
          build-args: |
            PORT=3000
            NODE_ENV=production
            AUTH_CLIENT_ID=${{ secrets.AUTH_CLIENT_ID }}
            AUTH_CLIENT_SECRET=${{ secrets.AUTH_CLIENT_SECRET }}
            SESSION_SECRET=${{ secrets.SESSION_SECRET }}
            CALLBACK_URL=${{ secrets.CALLBACK_URL }}
            ALLOWED_USERS=${{ secrets.ALLOWED_USERS }}
            DROPLET_IP=${{ secrets.DROPLET_IP }}
            DROPLET_USER=${{ secrets.DROPLET_USER }}
            DROPLET_SSH_KEY=${{ secrets.DROPLET_SSH_KEY }}

      # Deploy to Digital Ocean
      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository }}/cb-front:latest
            docker stop cb-front || true
            docker rm cb-front || true
            docker run -d \
              --name cb-front \
              -p 3001:3000 \
              ghcr.io/${{ github.repository }}/cb-front:latest
